### ISSUE TITLE
Tardis Landing Console Word Spam

### ISSUE THREAD

**Issue by lukasz4488** [mistersecret312/TAdditions#4]
Whenever anyone on the server will try to land their time ship, the server console has the message "pain3" added before the cursor.
Is it bug or an Easter Egg?
If it is the second than please remove it because it is annoying.

**Comment by mistersecret312** [comment]
Removed in dev(will be out when next patch is)

This print was used to find issues with custom subsystems, and included 'pain', 'pain2' as well as already mentioned 'pain3', and only the latter ran on correct functioning. These names came from how painful it was to make it work.

**Comment by Suff99** [comment]
That's actually incredibly funny

**Comment by mistersecret312** [comment]
No, it is not, wasting weeks on that was not funny.(And yeah I did forget to remove the prints)

**Comment by Suff99** [comment]
I meant the print outs haha
